# Generated by Django 2.1.3 on 2019-07-28 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('mrp', models.CharField(max_length=50)),
                ('saving', models.CharField(max_length=50)),
                ('url', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.date.today, max_length=50)),
                ('other_images', models.TextField()),
                ('android', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=32)),
                ('weight', models.CharField(max_length=32)),
                ('battery', models.CharField(max_length=32)),
                ('display', models.CharField(max_length=32)),
            ],
        ),
    ]
