# Generated by Django 2.1.3 on 2019-07-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='pub_date',
        ),
    ]
