# Generated by Django 2.1.3 on 2019-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190728_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
