# Generated by Django 2.1.3 on 2019-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190802_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_on_amazon',
            field=models.IntegerField(max_length=50),
        ),
    ]
