# Generated by Django 2.1.3 on 2019-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190803_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=255),
        ),
    ]
